name: 'Files Changed'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v8.4

      - name: Get specific changed files
        id: package-lock-check
        uses: tj-actions/changed-files@v8.4
        with:
          files: |
            package-lock.json

      - name: Comment on PR
        uses: actions/github-script@v4
        if: steps.package-lock-check.outputs.any_changed == 'true'
        env:
          FILES: ${{ steps.changed-files.outputs.all_modified_files }}
        with:
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            console.log(context);
            console.log('FILES', process.env.FILES);

            const parts = ["To avoid a blocking Change Request, ensure that the `package-lock.json` has not changed unexpectedly.",
                ...(process.env.FILES.split(' ').map((f) => {
                    if (f.includes("package-lock.json")) {
                        return `- [ ] \`${f}\` has no unexpected changes`
                    }
                }).filter(e => e))
            ];

            github.issues.createComment({
              issue_number,
              owner,
              repo,
              body: parts.join("\n")
            })
