name: 'Files Changed'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get specific changed files
        id: package-lock-check
        uses: tj-actions/changed-files@v8.4
        with:
          files: |
            package-lock.json

      - name: List all added files
        if: steps.package-lock-check.outputs.any_changed == 'true'
        run: |
          export _MSG=$(printf "%s\n" "Lock file changes:")
          for file in "${{ steps.package-lock-check.added_files }}"; do
            _MSG+=$(printf "\n%s" "\`$file\`")
          done
          export MSG="$_MSG"
          echo "::set-env name=MSG::$MSG"

      - name: comment PR
        uses: unsplash/comment-on-pr@master
        if: steps.package-lock-check.outputs.any_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ env.MSG }}
          check_for_duplicate_msg: true