name: 'package-lock.json check'

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v8.4

      - name: Get specific changed files
        id: package-lock-check
        uses: tj-actions/changed-files@v8.4
        with:
          files: |
            package-lock.json

      - name: Build comment
        uses: actions/github-script@v4
        id: comment
        if: steps.package-lock-check.outputs.any_changed == 'true'
        env:
          FILES: ${{ steps.changed-files.outputs.all_modified_files }}
        with:
          result-encoding: string
          script: |
            console.log(context);

            const files = await github.pulls.listFiles({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            console.log('FILES', files);

            const parts = [
                "Ensure that the `package-lock.json` has not changed unexpectedly.",
                ...(process.env.FILES.split(' ').map((f) => {
                    if (f.includes("package-lock.json")) {
                        return `- [ ] \`${f}\` has no unexpected changes`
                    }
                }).filter(e => e))
            ];

            return parts.join("\n")

      - name: Add sticky comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.package-lock-check.outputs.any_changed == 'true'
        with:
          header: package-lock.json notice
          message: ${{ steps.comment.outputs.result }}

      - name: Remove comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.package-lock-check.outputs.any_changed == 'false'
        with:
          header: package-lock.json notice
          delete: true
